name: Heimdall
version: ${project.version}
main: me.affanhaq.mapcha.Mapcha
description: A simple captcha plugin, which uses maps as the captcha.
depend:
  - AuthMe

permissions:
  heimdall.bypass:
    desciption: Allows you to bypass the captcha.
    default: op

commands:
  captcha:
    description: Captcha command
    usage: /captcha <your captcha>
  join:
    description: Makes you join the server loool
    usage: /join
  regenSecret:
    description: Regenerates and posts secret again, if enabled.
    usage: /regenSecret
  discord:
    description: Shows discord linnk
    usage: /discord