name: Mapcha
version: 2.0
main: me.affanhaq.mapcha.Mapcha
description: A simple captcha plugin, which uses maps as the captcha.
softdepend:
  - AuthMe

permissions:
  mapcha.bypass:
    desciption: Allows you to bypass the captcha.
    default: op

commands:
  captcha:
    description: Captcha command
    usage: /captcha <your captcha>
  join:
    description: Makes you join the server loool
    usage: /join